{
 "title": "5G Network Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheus_datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "charm",
    "label": "Charm",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "UPF Status",
   "type": "table",
   "description": "UPF Status",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{juju_charm=\"sdcore-upf-k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5G Core subscribers",
   "type": "table",
   "description": "5G Core subscribers",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "smf_pdu_session_profile", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5G Active PDU Sessions",
   "type": "stat",
   "description": "5G Active PDU Sessions",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smf_pdu_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPF Uplink Throughput",
   "type": "timeseries",
   "description": "UPF Uplink Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\"}[2m])",
     "legendFormat": "{{juju_application}}"
    }
   ]
  },
  {
   "title": "UPF Downlink Throughput",
   "type": "timeseries",
   "description": "UPF Downlink Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Access\"}[2m])",
     "legendFormat": "{{juju_application}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{charm=~\"$charm\"} |= ``"
    }
   ]
  }
 ]
}