name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install Grafana Dashboard Linter
        run: go install github.com/grafana/dashboard-linter@latest
      - name: Run Grafana Dashboard Lint
        run: dashboard-linter lint grafana_dashboards/sdcore/5g_network.json
